development:
  dialect: mysql 
  database: vuerecipe_development
  user: test
  password: test
  #host: 127.0.0.1
  pool: 5

test:
  url: {{envOr "TEST_DATABASE_URL" "mysql://test:test@/vuerecipe_development?multiStatements=true"}}

production:
  url: {{envOr "DATABASE_URL" "mysql://test:test@/vuerecipe_production?multiStatements=true"}}
